name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 'Documentation Updates'
    label: 'documentation'
  - title: 'Dependency Updates'
    label: 'dependency-updates'
  - title: 'Builds'
    label: 'builds'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  $CHANGES
