pull_request_rules:
  - name: assign and label scala-steward's PRs
    conditions:
      - author=scala-steward
    actions:
      assign:
        users: [NomadBlacky]
      label:
        add: [dependency-updates]
  - name: merge scala-steward's PRs
    conditions:
      - author=scala-steward
      - "status-success=sbt_tasks"
      # https://github.com/NomadBlacky/digdag-plugin-datadog/issues/75
      # - "status-success=test_digdag"
    actions:
      merge:
        method: squash
